### ISSUE TITLE
License

### ISSUE THREAD

**Issue by HarkonenBade** [DTCurrie/dice-boy#3]
The repo does not appear to currently have a license, it probably should have one and github offers an automated way to easily add major common licenses.

**Comment by DTCurrie** [comment]
Yeah, I never really intended this to be a public thing. I just used it with my personal group and made it public so someone who was getting into programming could take a look at it. I'll have to go through and set everything up since evidently there is interest in the bot.

**Comment by DTCurrie** [comment]
Added a license,
